### ISSUE TITLE
[Bug] RuntimeError: The size of tensor a (576) must match the size of tensor b (432) at non-singleton dimension 1

### ISSUE THREAD

**Issue by smallccn** [open-mmlab/mmrazor#101]
Dear Sir,

When I try to follow the guide to do a pruning with an exist model, below error is occured. 

cmd:
python ./tools/model_converters/split_checkpoint.py \
  configs/pruning/autoslim/autoslim_mbv2_subnet_8xb256_in1k.py \
  /my_local_path/mobilenet_v2_batch256_imagenet_20200708-3b2dc3af.pth \
  --channel-cfgs configs/pruning/autoslim/AUTOSLIM_MBV2_530M_OFFICIAL.yaml

note: mobilenet_v2_batch256_imagenet_20200708-3b2dc3af.pth is downloading from (https://download.openmmlab.com/mmclassification/v0/mobilenet_v2/mobilenet_v2_batch256_imagenet_20200708-3b2dc3af.pth)

after run above command, some error is printed.

Traceback (most recent call last):
  File "/my_local_path/workspace/mmrazor/mmrazor/models/algorithms/autoslim.py", line 76, in _init_pruner
    pseudo_architecture.forward_dummy(pseudo_img)
  File "/my_local_path/workspace/mmrazor/mmrazor/models/architectures/mmcls.py", line 20, in forward_dummy
    output = child(output)
  File "/my_local_path/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in
    return forward_call(*input, **kwargs)
  File "/my_local_path/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcls/models/backbones/mobilenet_v2.py", li
    x = layer(x)
  File "/my_local_path/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in
    return forward_call(*input, **kwargs)
  File "/my_local_path/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, i
    input = module(input)
  File "/my_local_path/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in
    return forward_call(*input, **kwargs)
  File "/my_local_path/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcls/models/backbones/mobilenet_v2.py", li
    out = _inner_forward(x)
  File "/my_local_path/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcls/models/backbones/mobilenet_v2.py", li
    return x + self.conv(x)
  File "/my_local_path/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in
    return forward_call(*input, **kwargs)
  File "/my_local_path/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, i
    input = module(input)
  File "/my_local_path/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in
    return forward_call(*input, **kwargs)
  File "/my_local_path/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/cnn/bricks/conv_module.py", line 201,
    x = self.conv(x)
  File "/my_local_path/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in
    return forward_call(*input, **kwargs)
  File "/my_local_path/workspace/mmrazor/mmrazor/models/pruners/structure_pruning.py", line 371, in modified_forward
    feature = feature * self.in_mask
RuntimeError: The size of tensor a (576) must match the size of tensor b (432) at non-singleton dimension 1

Could you please help to guide for this, thanks?

**Comment by smallccn** [comment]
Btw, for the guide of autoslim, I can't find the url for supernet, so I download it from openmmlab.

**Comment by pppppM** [comment]
Have you completed the three steps before split ckpt?
After completing these three steps, three pruned models will be obtained, but the ckpts of these three models are coupled together.
