### ISSUE TITLE
KeyError: 'SegLocalVisualizer is not in the visualizer registry. Please check whether the value of `SegLocalVisualizer` is correct or it was registered as expected.

### ISSUE THREAD

**Issue by He-Yingchao** [open-mmlab/mmrazor#369]
### Checklist

- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

I have installed “mmrazor(version=dev 1.x)" according to the 'installation.md', but an error occured when installing the "mmseg" library in the last step ("mim install 'mmseg>=1.0.0rc0'"). How can I install the "mmseg" library? (mmsegmentation has been installed manually).

### Post related information

1. The output of `pip list | grep "mmcv\|mmrazor\|^torch"`
mmcls              1.0.0rc3
mmcv               2.0.0rc3
mmdet              3.0.0rc4
mmengine           0.3.2     /home/dream007/openmmlab2.0/mmengine
mmrazor            1.0.0rc1  /home/dream007/openmmlab2.0/mmengine/mmrazor
mmsegmentation     1.0.0rc1  /home/dream007/openmmlab2.0/mmsegmentation
torch              1.10.1
torchaudio         0.10.1
torchvision        0.11.2

2. Your config file if you modified it or created a new one.

```python
2022/12/01 16:48:31 - mmengine - INFO - 
------------------------------------------------------------
System environment:
    sys.platform: linux
    Python: 3.8.15 (default, Nov 24 2022, 15:19:38) [GCC 11.2.0]
    CUDA available: True
    numpy_random_seed: 1230765142
    GPU 0: NVIDIA GeForce RTX 3080
    CUDA_HOME: /usr/local/cuda-11.4
    NVCC: Cuda compilation tools, release 11.4, V11.4.48
    GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
    PyTorch: 1.10.1
    PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

    TorchVision: 0.11.2
    OpenCV: 4.6.0
    MMEngine: 0.3.2

Runtime environment:
    cudnn_benchmark: True
    mp_cfg: {'mp_start_method': 'fork', 'opencv_num_threads': 0}
    dist_cfg: {'backend': 'nccl'}
    seed: None
    Distributed launcher: none
    Distributed training: False
    GPU number: 1
------------------------------------------------------------

2022/12/01 16:48:31 - mmengine - INFO - Config:
dataset_type = 'CityscapesDataset'
data_root = 'data/cityscapes/'
crop_size = (512, 1024)
train_pipeline = [
    dict(type='LoadImageFromFile', _scope_='mmseg'),
    dict(type='LoadAnnotations', _scope_='mmseg'),
    dict(
        type='RandomResize',
        scale=(2048, 1024),
        ratio_range=(0.5, 2.0),
        keep_ratio=True,
        _scope_='mmseg'),
    dict(
        type='RandomCrop',
        crop_size=(512, 1024),
        cat_max_ratio=0.75,
        _scope_='mmseg'),
    dict(type='RandomFlip', prob=0.5, _scope_='mmseg'),
    dict(type='PhotoMetricDistortion', _scope_='mmseg'),
    dict(type='PackSegInputs', _scope_='mmseg')
]
test_pipeline = [
    dict(type='LoadImageFromFile', _scope_='mmseg'),
    dict(type='Resize', scale=(2048, 1024), keep_ratio=True, _scope_='mmseg'),
    dict(type='LoadAnnotations', _scope_='mmseg'),
    dict(type='PackSegInputs', _scope_='mmseg')
]
train_dataloader = dict(
    batch_size=2,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='InfiniteSampler', shuffle=True, _scope_='mmseg'),
    dataset=dict(
        type='CityscapesDataset',
        data_root='data/cityscapes/',
        data_prefix=dict(
            img_path='leftImg8bit/train', seg_map_path='gtFine/train'),
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations'),
            dict(
                type='RandomResize',
                scale=(2048, 1024),
                ratio_range=(0.5, 2.0),
                keep_ratio=True),
            dict(type='RandomCrop', crop_size=(512, 1024), cat_max_ratio=0.75),
            dict(type='RandomFlip', prob=0.5),
            dict(type='PhotoMetricDistortion'),
            dict(type='PackSegInputs')
        ],
        _scope_='mmseg'))
val_dataloader = dict(
    batch_size=1,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False, _scope_='mmseg'),
    dataset=dict(
        type='CityscapesDataset',
        data_root='data/cityscapes/',
        data_prefix=dict(
            img_path='leftImg8bit/val', seg_map_path='gtFine/val'),
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', scale=(2048, 1024), keep_ratio=True),
            dict(type='LoadAnnotations'),
            dict(type='PackSegInputs')
        ],
        _scope_='mmseg'))
test_dataloader = dict(
    batch_size=1,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False, _scope_='mmseg'),
    dataset=dict(
        type='CityscapesDataset',
        data_root='data/cityscapes/',
        data_prefix=dict(
            img_path='leftImg8bit/val', seg_map_path='gtFine/val'),
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', scale=(2048, 1024), keep_ratio=True),
            dict(type='LoadAnnotations'),
            dict(type='PackSegInputs')
        ],
        _scope_='mmseg'))
val_evaluator = dict(type='IoUMetric', iou_metrics=['mIoU'], _scope_='mmseg')
test_evaluator = dict(type='IoUMetric', iou_metrics=['mIoU'], _scope_='mmseg')
optimizer = dict(
    type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0005, _scope_='mmseg')
optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0005),
    clip_grad=dict(max_norm=25, norm_type=2))
param_scheduler = [
    dict(type='LinearLR', by_epoch=False, start_factor=0.1, begin=0, end=200),
    dict(
        type='PolyLR',
        eta_min=0.0001,
        power=0.9,
        begin=200,
        end=80000,
        by_epoch=False)
]
train_cfg = dict(
    type='IterBasedTrainLoop',
    max_iters=160000,
    val_interval=800,
    _scope_='mmseg')
val_cfg = dict(type='ValLoop', _scope_='mmseg')
test_cfg = dict(type='TestLoop', _scope_='mmseg')
default_hooks = dict(
    timer=dict(type='IterTimerHook', _scope_='mmseg'),
    logger=dict(
        type='LoggerHook',
        interval=50,
        log_metric_by_epoch=False,
        _scope_='mmseg'),
    param_scheduler=dict(type='ParamSchedulerHook', _scope_='mmseg'),
    checkpoint=dict(
        type='CheckpointHook', by_epoch=False, interval=16000,
        _scope_='mmseg'),
    sampler_seed=dict(type='DistSamplerSeedHook', _scope_='mmseg'),
    visualization=dict(type='SegVisualizationHook', _scope_='mmseg'))
default_scope = 'mmseg'
env_cfg = dict(
    cudnn_benchmark=True,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'))
vis_backends = [dict(type='LocalVisBackend', _scope_='mmseg')]
visualizer = dict(
    type='SegLocalVisualizer',
    vis_backends=[dict(type='LocalVisBackend')],
    name='visualizer',
    _scope_='mmseg')
log_processor = dict(by_epoch=False)
log_level = 'INFO'
load_from = None
resume = False
data_preprocessor = dict(
    _scope_='mmseg',
    type='SegDataPreProcessor',
    mean=[123.675, 116.28, 103.53],
    std=[58.395, 57.12, 57.375],
    bgr_to_rgb=True,
    size=(512, 1024),
    pad_val=0,
    seg_pad_val=255)
architecture = dict(
    _scope_='mmseg',
    type='CascadeEncoderDecoder',
    data_preprocessor=dict(
        _scope_='mmseg',
        type='SegDataPreProcessor',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        bgr_to_rgb=True,
        size=(512, 1024),
        pad_val=0,
        seg_pad_val=255),
    num_stages=2,
    pretrained=None,
    backbone=dict(
        type='ResNetV1c',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        dilations=(1, 1, 1, 1),
        strides=(1, 2, 2, 2),
        norm_eval=False,
        style='pytorch',
        contract_dilation=True),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=4),
    decode_head=[
        dict(
            type='FPNHead',
            in_channels=[256, 256, 256, 256],
            in_index=[0, 1, 2, 3],
            feature_strides=[4, 8, 16, 32],
            channels=128,
            dropout_ratio=-1,
            num_classes=19,
            align_corners=False,
            loss_decode=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
        dict(
            type='PointHead',
            in_channels=[256],
            in_index=[0],
            channels=256,
            num_fcs=3,
            coarse_pred_each_layer=True,
            dropout_ratio=-1,
            num_classes=19,
            align_corners=False,
            loss_decode=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0))
    ],
    train_cfg=dict(
        num_points=2048, oversample_ratio=3, importance_sample_ratio=0.75),
    test_cfg=dict(
        mode='whole',
        subdivision_steps=2,
        subdivision_num_points=8196,
        scale_factor=2))
stage_ratio_1 = 0.65
stage_ratio_2 = 0.6
stage_ratio_3 = 0.9
stage_ratio_4 = 0.7
target_pruning_ratio = dict({
    'backbone.layer1.0.conv1_(0, 64)_64': 0.65,
    'backbone.layer1.0.conv2_(0, 64)_64': 0.6,
    'backbone.layer1.0.conv3_(0, 256)_256': 0.9,
    'backbone.layer1.1.conv1_(0, 64)_64': 0.65,
    'backbone.layer1.1.conv2_(0, 64)_64': 0.6,
    'backbone.layer1.2.conv1_(0, 64)_64': 0.65,
    'backbone.layer1.2.conv2_(0, 64)_64': 0.6,
    'backbone.layer2.0.conv1_(0, 128)_128': 0.65,
    'backbone.layer2.0.conv2_(0, 128)_128': 0.6,
    'backbone.layer2.0.conv3_(0, 512)_512': 0.9,
    'backbone.layer2.1.conv1_(0, 128)_128': 0.65,
    'backbone.layer2.1.conv2_(0, 128)_128': 0.6,
    'backbone.layer2.2.conv1_(0, 128)_128': 0.65,
    'backbone.layer2.2.conv2_(0, 128)_128': 0.6,
    'backbone.layer2.3.conv1_(0, 128)_128': 0.65,
    'backbone.layer2.3.conv2_(0, 128)_128': 0.6,
    'backbone.layer3.0.conv1_(0, 256)_256': 0.65,
    'backbone.layer3.0.conv2_(0, 256)_256': 0.6,
    'backbone.layer3.0.conv3_(0, 1024)_1024': 0.9,
    'backbone.layer3.1.conv1_(0, 256)_256': 0.65,
    'backbone.layer3.1.conv2_(0, 256)_256': 0.6,
    'backbone.layer3.2.conv1_(0, 256)_256': 0.65,
    'backbone.layer3.2.conv2_(0, 256)_256': 0.6,
    'backbone.layer3.3.conv1_(0, 256)_256': 0.7,
    'backbone.layer3.3.conv2_(0, 256)_256': 0.7,
    'backbone.layer3.4.conv1_(0, 256)_256': 0.7,
    'backbone.layer3.4.conv2_(0, 256)_256': 0.7,
    'backbone.layer3.5.conv1_(0, 256)_256': 0.7,
    'backbone.layer3.5.conv2_(0, 256)_256': 0.7,
    'backbone.layer4.0.conv1_(0, 512)_512': 0.7,
    'backbone.layer4.0.conv2_(0, 512)_512': 0.7,
    'backbone.layer4.0.conv3_(0, 2048)_2048': 0.9,
    'backbone.layer4.1.conv1_(0, 512)_512': 0.7,
    'backbone.layer4.1.conv2_(0, 512)_512': 0.7,
    'backbone.layer4.2.conv1_(0, 512)_512': 0.7,
    'backbone.layer4.2.conv2_(0, 512)_512': 0.7
})
model = dict(
    _scope_='mmrazor',
    type='DCFF',
    architecture=dict(
        cfg_path='mmcls::resnet/resnet50_8xb32_in1k.py', pretrained=False),
    mutator_cfg=dict(
        type='DCFFChannelMutator',
        channel_unit_cfg=dict(
            type='DCFFChannelUnit',
            units='configs/pruning/mmseg/dcff/resnet_seg.json'),
        parse_cfg=dict(
            type='BackwardTracer',
            loss_calculator=dict(type='CascadeEncoderDecoderPseudoLoss'))),
    target_pruning_ratio=dict({
        'backbone.layer1.0.conv1_(0, 64)_64': 0.65,
        'backbone.layer1.0.conv2_(0, 64)_64': 0.6,
        'backbone.layer1.0.conv3_(0, 256)_256': 0.9,
        'backbone.layer1.1.conv1_(0, 64)_64': 0.65,
        'backbone.layer1.1.conv2_(0, 64)_64': 0.6,
        'backbone.layer1.2.conv1_(0, 64)_64': 0.65,
        'backbone.layer1.2.conv2_(0, 64)_64': 0.6,
        'backbone.layer2.0.conv1_(0, 128)_128': 0.65,
        'backbone.layer2.0.conv2_(0, 128)_128': 0.6,
        'backbone.layer2.0.conv3_(0, 512)_512': 0.9,
        'backbone.layer2.1.conv1_(0, 128)_128': 0.65,
        'backbone.layer2.1.conv2_(0, 128)_128': 0.6,
        'backbone.layer2.2.conv1_(0, 128)_128': 0.65,
        'backbone.layer2.2.conv2_(0, 128)_128': 0.6,
        'backbone.layer2.3.conv1_(0, 128)_128': 0.65,
        'backbone.layer2.3.conv2_(0, 128)_128': 0.6,
        'backbone.layer3.0.conv1_(0, 256)_256': 0.65,
        'backbone.layer3.0.conv2_(0, 256)_256': 0.6,
        'backbone.layer3.0.conv3_(0, 1024)_1024': 0.9,
        'backbone.layer3.1.conv1_(0, 256)_256': 0.65,
        'backbone.layer3.1.conv2_(0, 256)_256': 0.6,
        'backbone.layer3.2.conv1_(0, 256)_256': 0.65,
        'backbone.layer3.2.conv2_(0, 256)_256': 0.6,
        'backbone.layer3.3.conv1_(0, 256)_256': 0.7,
        'backbone.layer3.3.conv2_(0, 256)_256': 0.7,
        'backbone.layer3.4.conv1_(0, 256)_256': 0.7,
        'backbone.layer3.4.conv2_(0, 256)_256': 0.7,
        'backbone.layer3.5.conv1_(0, 256)_256': 0.7,
        'backbone.layer3.5.conv2_(0, 256)_256': 0.7,
        'backbone.layer4.0.conv1_(0, 512)_512': 0.7,
        'backbone.layer4.0.conv2_(0, 512)_512': 0.7,
        'backbone.layer4.0.conv3_(0, 2048)_2048': 0.9,
        'backbone.layer4.1.conv1_(0, 512)_512': 0.7,
        'backbone.layer4.1.conv2_(0, 512)_512': 0.7,
        'backbone.layer4.2.conv1_(0, 512)_512': 0.7,
        'backbone.layer4.2.conv2_(0, 512)_512': 0.7
    }),
    step_freq=200,
    linear_schedule=False,
    is_deployed=False)
model_wrapper = dict(
    type='mmcv.MMDistributedDataParallel', find_unused_parameters=True)
launcher = 'none'
work_dir = 'hyc_razor'

2022/12/01 16:48:31 - mmengine - INFO - Result has been saved to /home/dream007/openmmlab2.0/mmengine/mmrazor/hyc_razor/modules_statistic_results.json
2022/12/01 16:48:31 - mmengine - WARNING - mmseg is not installed and its modules will not be registered. If you want to use modules defined in mmseg, Please install mmseg by `pip install mmsegmentation.
```

3. Your train log file if you meet the problem during training.
'''bash
python tools/train.py my_model/dcff_pointrend_resnet50_8xb2_cityscapes.py --work-dir hyc_razor
'''

4. Other code you modified in the `mmrazor` folder.
Training 'pruning/mmseg/dcff/dcff_pointrend_resnet50_8xb2_cityscapes.py' on my own dataset.

**Comment by HIT-cwh** [comment]
Hi! Could you check if the following codes work well:
```
from importlib import import_module
module = import_module(f'mmseg.utils')
module.register_all_modules(False)
```

**Comment by He-Yingchao** [comment]
> 
Thank you for your answer. I ran the code you mentioned and got the following error.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dream007/openmmlab2.0/mmsegmentation/mmseg/utils/set_env.py", line 19, in register_all_modules
    import mmseg.datasets  # noqa: F401,F403
  File "/home/dream007/openmmlab2.0/mmsegmentation/mmseg/datasets/__init__.py", line 27, in <module>
    from .my_dataset import MyDataset
  File "/home/dream007/openmmlab2.0/mmsegmentation/mmseg/datasets/my_dataset.py", line 4, in <module>
    from .builder import DATASETS
ModuleNotFoundError: No module named 'mmseg.datasets.builder'

**Comment by He-Yingchao** [comment]
> 



> 
When I installed the mmseg library according to the official tutorial instruction "mim install 'mmseg>=1.0.0rc0'", the following error was reported.
Collecting mmseg>=1.0.0rc0
  Using cached mmseg-1.3.0.tar.gz (817 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-9npm3pqr/mmseg_a6d657794f9a45a2bd1f008d59dcd58a/setup.py", line 6, in <module>
          reload(sys)
      NameError: name 'reload' is not defined
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I did not report an error when installing the 'mmcls' and 'mmdet' libraries, but the installation of the 'mmseg' library always reported an error. I've tried many possible solutions and don't know what to do anymore.

**Comment by He-Yingchao** [comment]
> 



> 


> Hi! Could you check if the following codes work well:
> 
> ```
> from importlib import import_module
> module = import_module(f'mmseg.utils')
> module.register_all_modules(False)
> ```

When I installed the mmseg library according to the official tutorial instruction "mim install 'mmseg>=1.0.0rc0'", the following error was reported.
Collecting mmseg>=1.0.0rc0
  Using cached mmseg-1.3.0.tar.gz (817 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-9npm3pqr/mmseg_a6d657794f9a45a2bd1f008d59dcd58a/setup.py", line 6, in <module>
          reload(sys)
      NameError: name 'reload' is not defined
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I did not report an error when installing the 'mmcls' and 'mmdet' libraries, but the installation of the 'mmseg' library always reported an error. I've tried many possible solutions and don't know what to do anymore.

**Comment by He-Yingchao** [comment]
> Hi! Could you check if the following codes work well:
> 
> ```
> from importlib import import_module
> module = import_module(f'mmseg.utils')
> module.register_all_modules(False)
> ```

Thank you for your answer. I ran the code you mentioned and got the following error.
Traceback (most recent call last):
File "", line 1, in
File "/home/dream007/openmmlab2.0/mmsegmentation/mmseg/utils/set_env.py", line 19, in register_all_modules
import mmseg.datasets # noqa: F401,F403
File "/home/dream007/openmmlab2.0/mmsegmentation/mmseg/datasets/init.py", line 27, in
from .my_dataset import MyDataset
File "/home/dream007/openmmlab2.0/mmsegmentation/mmseg/datasets/my_dataset.py", line 4, in
from .builder import DATASETS
ModuleNotFoundError: No module named 'mmseg.datasets.builder'

> Hi! Could you check if the following codes work well:
> 
> ```
> from importlib import import_module
> module = import_module(f'mmseg.utils')
> module.register_all_modules(False)
> ```

Thank you for your answer. I ran the code you mentioned and got the following error.
Traceback (most recent call last):
File "", line 1, in
File "/home/dream007/openmmlab2.0/mmsegmentation/mmseg/utils/set_env.py", line 19, in register_all_modules
import mmseg.datasets # noqa: F401,F403
File "/home/dream007/openmmlab2.0/mmsegmentation/mmseg/datasets/init.py", line 27, in
from .my_dataset import MyDataset
File "/home/dream007/openmmlab2.0/mmsegmentation/mmseg/datasets/my_dataset.py", line 4, in
from .builder import DATASETS
ModuleNotFoundError: No module named 'mmseg.datasets.builder'

**Comment by HIT-cwh** [comment]
It seems that there is no module named 'mmseg.datasets.builder'.  (Refer to https://github.com/open-mmlab/mmsegmentation/tree/dev-1.x/mmseg/datasets.) 
This is what we did in master branch but we are using dev-1.x now?
