### ISSUE TITLE
[Bug] AttributeError: 'ConfigDict' object has no attribute 'searcher' for DARTS

### ISSUE THREAD

**Issue by Debrove** [open-mmlab/mmrazor#382]
### Describe the bug

I got AttributeError: 'ConfigDict' object has no attribute 'searcher' when I search on DARTS.

It seems that mmrazor has GreedySearcher() and EvolutionSearcher(), but not for DARTS.

Please help me if I miss something in the config. Thank you very much!

### To Reproduce

The command you executed.

```shell
CUDA_VISIBLE_DEVICES=0 python ./tools/mmcls/search_mmcls.py   configs/nas/darts/darts_supernet_unroll_1xb64_cifar10.py   none   --work-dir logs/darts
```

### Post related information

1. The output of `pip list | grep "mmcv\|mmrazor\|^torch"`
mmcv-full               1.5.0
mmrazor                 0.3.1
torch                   1.12.1+cu116
torchvision             0.13.1+cu116
2. Your config file if you modified it or created a new one.
No modified config file

3. Your train log file if you meet the problem during training.
   /data/hwzheng/anaconda3/envs/open-mmlab/bin/python3.7 /data/hwzheng/Downloads/pycharm-community-2021.2.3/plugins/python-ce/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 42859 --file /data/hwzheng/mmrazor/tools/mmcls/search_mmcls.py configs/nas/darts/darts_supernet_unroll_1xb64_cifar10.py none --work-dir logs/darts
Connected to pydev debugger (build 212.5457.59)
/data/hwzheng/mmrazor/mmrazor/utils/setup_env.py:33: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  f'Setting OMP_NUM_THREADS environment variable for each process '
/data/hwzheng/mmrazor/mmrazor/utils/setup_env.py:43: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  f'Setting MKL_NUM_THREADS environment variable for each process '
2022-12-06 15:19:48,920 - mmcls - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0: Tesla V100S-PCIE-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.5, V11.5.50
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.12.1+cu116
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 
TorchVision: 0.13.1+cu116
OpenCV: 4.6.0
MMCV: 1.5.0
MMCV Compiler: GCC 9.4
MMCV CUDA Compiler: 11.5
MMClassification: 0.24.1+a0aff4d
------------------------------------------------------------
2022-12-06 15:19:48,921 - mmcls - INFO - Distributed training: False
2022-12-06 15:19:49,765 - mmcls - INFO - Config:
dataset_type = 'CIFAR10'
img_norm_cfg = dict(
    mean=[125.307, 122.961, 113.8575],
    std=[51.5865, 50.847, 51.255],
    to_rgb=False)
train_pipeline = [
    dict(type='RandomCrop', size=32, padding=4),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(
        type='Normalize',
        mean=[125.307, 122.961, 113.8575],
        std=[51.5865, 50.847, 51.255],
        to_rgb=False),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]
test_pipeline = [
    dict(
        type='Normalize',
        mean=[125.307, 122.961, 113.8575],
        std=[51.5865, 50.847, 51.255],
        to_rgb=False),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img'])
]
data = dict(
    samples_per_gpu=64,
    workers_per_gpu=8,
    train=dict(
        type='CIFAR10',
        data_prefix='data/cifar10',
        pipeline=[
            dict(type='RandomCrop', size=32, padding=4),
            dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
            dict(
                type='Normalize',
                mean=[125.307, 122.961, 113.8575],
                std=[51.5865, 50.847, 51.255],
                to_rgb=False),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='ToTensor', keys=['gt_label']),
            dict(type='Collect', keys=['img', 'gt_label'])
        ]),
    val=dict(
        type='CIFAR10',
        data_prefix='data/cifar10',
        pipeline=[
            dict(
                type='Normalize',
                mean=[125.307, 122.961, 113.8575],
                std=[51.5865, 50.847, 51.255],
                to_rgb=False),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ],
        test_mode=True),
    test=dict(
        type='CIFAR10',
        data_prefix='data/cifar10',
        pipeline=[
            dict(
                type='Normalize',
                mean=[125.307, 122.961, 113.8575],
                std=[51.5865, 50.847, 51.255],
                to_rgb=False),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ],
        test_mode=True),
    split=True)
checkpoint_config = dict(interval=1)
log_config = dict(interval=100, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
model = dict(
    type='mmcls.ImageClassifier',
    backbone=dict(
        type='DartsBackbone',
        in_channels=3,
        base_channels=16,
        num_layers=8,
        num_nodes=4,
        stem_multiplier=3,
        out_indices=(7, )),
    neck=dict(type='GlobalAveragePooling'),
    head=dict(
        type='LinearClsHead',
        num_classes=10,
        in_channels=256,
        loss=dict(type='CrossEntropyLoss', loss_weight=1.0),
        topk=(1, 5),
        cal_acc=True),
    pretrained=None)
algorithm = dict(
    type='Darts',
    architecture=dict(
        type='MMClsArchitecture',
        model=dict(
            type='mmcls.ImageClassifier',
            backbone=dict(
                type='DartsBackbone',
                in_channels=3,
                base_channels=16,
                num_layers=8,
                num_nodes=4,
                stem_multiplier=3,
                out_indices=(7, )),
            neck=dict(type='GlobalAveragePooling'),
            head=dict(
                type='LinearClsHead',
                num_classes=10,
                in_channels=256,
                loss=dict(type='CrossEntropyLoss', loss_weight=1.0),
                topk=(1, 5),
                cal_acc=True))),
    mutator=dict(
        type='DartsMutator',
        placeholder_mapping=dict(
            node=dict(
                type='DifferentiableOP',
                with_arch_param=True,
                choices=dict(
                    zero=dict(type='DartsZero'),
                    skip_connect=dict(
                        type='DartsSkipConnect',
                        norm_cfg=dict(type='BN', affine=False)),
                    max_pool_3x3=dict(
                        type='DartsPoolBN',
                        pool_type='max',
                        norm_cfg=dict(type='BN', affine=False)),
                    avg_pool_3x3=dict(
                        type='DartsPoolBN',
                        pool_type='avg',
                        norm_cfg=dict(type='BN', affine=False)),
                    sep_conv_3x3=dict(
                        type='DartsSepConv',
                        kernel_size=3,
                        norm_cfg=dict(type='BN', affine=False)),
                    sep_conv_5x5=dict(
                        type='DartsSepConv',
                        kernel_size=5,
                        norm_cfg=dict(type='BN', affine=False)),
                    dil_conv_3x3=dict(
                        type='DartsDilConv',
                        kernel_size=3,
                        norm_cfg=dict(type='BN', affine=False)),
                    dil_conv_5x5=dict(
                        type='DartsDilConv',
                        kernel_size=5,
                        norm_cfg=dict(type='BN', affine=False)))),
            node_edge=dict(
                type='DifferentiableEdge', num_chosen=2,
                with_arch_param=False))),
    retraining=False,
    unroll=True)
optimizer = dict(
    architecture=dict(type='SGD', lr=0.025, momentum=0.9, weight_decay=0.0003),
    mutator=dict(type='Adam', lr=0.0003, weight_decay=0.001))
optimizer_config = None
lr_config = dict(
    policy='CosineAnnealing', min_lr=0.001, freeze_optimizers=['mutator'])
runner = dict(type='MultiLoaderEpochBasedRunner', max_epochs=50)
custom_hooks = [dict(type='SearchSubnetHook', interval=1, priority=70)]
find_unused_parameter = True
use_ddp_wrapper = True
work_dir = 'logs/darts'
/data/hwzheng/mmrazor/tools/mmcls/search_mmcls.py:150: UserWarning: Class names are not saved in the checkpoint's meta data, use imagenet by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '
2022-12-06 15:19:53,676 - mmcls - INFO - build search...
Traceback (most recent call last):
  File "/data/hwzheng/Downloads/pycharm-community-2021.2.3/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/data/hwzheng/Downloads/pycharm-community-2021.2.3/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/data/hwzheng/mmrazor/tools/mmcls/search_mmcls.py", line 184, in <module>
    main()
  File "/data/hwzheng/mmrazor/tools/mmcls/search_mmcls.py", line 171, in main
    cfg.searcher,
  File "/data/hwzheng/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 513, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/data/hwzheng/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 49, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'searcher'

4. Other code you modified in the `mmrazor` folder.
   \[here\]

### Additional context

\[here\]

**Comment by gaoyang07** [comment]
Thank you for your issue.

1. The `mmrazor:searcher` is not required for DARTS. DARTS is known as a classical NAS algorithm with constructing a matrix (refers to `alpha` in the paper) to build the search space, the structure of a single subnet in the built supernet of DARTS can be easily parsed according to the value of the mentioned matrix after supernet training, or so to speak, DARTS searches the subnet during supernet training (alternate optimization). The process is as follows:
   <img width="717" alt="image" src="https://user-images.githubusercontent.com/32762712/206082064-b3057569-1cb4-4c2c-beae-7b97f9971656.png">

2. By the way, you are welcomed to try our new branch `mmrazor:dev-1.x` instead of branch `master` to get more features with `OpenMMLab 2.0` project~

**Comment by Debrove** [comment]
Thanks! That's great! I will try it.
