### ISSUE TITLE
Provide the version adaptation table for mmrazor, mmcv, and mmcls

### ISSUE THREAD

**Issue by grapefruitL** [open-mmlab/mmrazor#393]
Can you provide the version adaptation table for mmrazor, mmcv, and mmcls? I used python 3.8 and reported the following errors according to the instructions
```
/opt/conda/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "/root/mmrazor/tools/mmcls/train_mmcls.py", line 13, in <module>
    from mmcls.datasets import build_dataset
  File "/opt/conda/lib/python3.8/site-packages/mmcls/datasets/__init__.py", line 2, in <module>
    from .base_dataset import BaseDataset
  File "/opt/conda/lib/python3.8/site-packages/mmcls/datasets/base_dataset.py", line 13, in <module>
    from mmcls.models.losses import accuracy
  File "/opt/conda/lib/python3.8/site-packages/mmcls/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/opt/conda/lib/python3.8/site-packages/mmcls/models/backbones/__init__.py", line 3, in <module>
    from .conformer import Conformer
  File "/opt/conda/lib/python3.8/site-packages/mmcls/models/backbones/conformer.py", line 9, in <module>
    from mmcv.cnn.bricks.transformer import AdaptivePadding
  File "/opt/conda/lib/python3.8/site-packages/mmcv/cnn/bricks/transformer.py", line 22, in <module>
    from mmcv.ops.multi_scale_deform_attn import \
  File "/opt/conda/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/opt/conda/lib/python3.8/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 15, in load_ext
    assert hasattr(ext, fun), f'{fun} miss in module {name}'
AssertionError: active_rotated_filter_forward miss in module _ext

```

**Comment by grapefruitL** [comment]
I try with following steps again
```
conda create -n openmmlab python=3.7 -y
conda activate openmmlab
conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.12.1/index.html
git clone https://github.com/open-mmlab/mmrazor.git
cd mmrazor
pip install -v -e .  # or "python setup.py develop"
```
it works with single gpu，but failed when distributed training, the error is:
```
Traceback (most recent call last):
  File "./tools/mmcls/train_mmcls.py", line 203, in <module>
    main()
  File "./tools/mmcls/train_mmcls.py", line 133, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/opt/conda/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 519, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/opt/conda/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 50, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'dist_params'
```
How to solve it? or just let me know that it doesn't support distributed training yet

**Comment by sunnyxiaohu** [comment]
Hi, I suggest you using https://github.com/open-mmlab/mim to install MMrazor and deps.
Btw, branch dev-1.x of MMrazor is supported and develped now.

**Comment by sunnyxiaohu** [comment]
https://github.com/open-mmlab/mmrazor/blob/dev-1.x/docs/en/get_started/installation.md

**Comment by grapefruitL** [comment]
Maybe it's the version of python, I use python3.8 before, now python3.7, everything is fine
