### ISSUE TITLE
[Bug]AssertionError: `iou3d_boxes_iou_bev_forward` miss in module _ext

### ISSUE THREAD

**Issue by minipuding** [open-mmlab/mmrazor#487]
### Describe the bug

The traceback are as follows:
```shell
Traceback (most recent call last):
  File "/nvme/xusijie/pjlab/projects/DD4PT/codes/tools/train.py", line 124, in <module>
    main()
  File "/nvme/xusijie/pjlab/projects/DD4PT/codes/tools/train.py", line 61, in main
    cfg = Config.fromfile(args.config)
  File "/nvme/xusijie/miniconda3/envs/sxu/lib/python3.9/site-packages/mmengine/config/config.py", line 181, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/nvme/xusijie/miniconda3/envs/sxu/lib/python3.9/site-packages/mmengine/utils/misc.py", line 77, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/nvme/xusijie/miniconda3/envs/sxu/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/nvme/xusijie/pjlab/projects/DD4PT/codes/dd4pt/__init__.py", line 1, in <module>
    from .ddmodel import Dd4ptModel, ProjectionHead
  File "/nvme/xusijie/pjlab/projects/DD4PT/codes/dd4pt/ddmodel.py", line 9, in <module>
    from mmrazor.models.utils import add_prefix
  File "/nvme/xusijie/miniconda3/envs/sxu/lib/python3.9/site-packages/mmrazor/models/__init__.py", line 12, in <module>
    from mmcls.models import *  # noqa: F401,F403
  File "/nvme/xusijie/miniconda3/envs/sxu/lib/python3.9/site-packages/mmcls/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/nvme/xusijie/miniconda3/envs/sxu/lib/python3.9/site-packages/mmcls/models/backbones/__init__.py", line 3, in <module>
    from .conformer import Conformer
  File "/nvme/xusijie/miniconda3/envs/sxu/lib/python3.9/site-packages/mmcls/models/backbones/conformer.py", line 9, in <module>
    from mmcv.cnn.bricks.transformer import AdaptivePadding
  File "/nvme/xusijie/miniconda3/envs/sxu/lib/python3.9/site-packages/mmcv/cnn/bricks/transformer.py", line 22, in <module>
    from mmcv.ops.multi_scale_deform_attn import \
  File "/nvme/xusijie/miniconda3/envs/sxu/lib/python3.9/site-packages/mmcv/ops/__init__.py", line 31, in <module>
    from .iou3d import boxes_iou_bev, nms_bev, nms_normal_bev
  File "/nvme/xusijie/miniconda3/envs/sxu/lib/python3.9/site-packages/mmcv/ops/iou3d.py", line 6, in <module>
    ext_module = ext_loader.load_ext('_ext', [
  File "/nvme/xusijie/miniconda3/envs/sxu/lib/python3.9/site-packages/mmcv/utils/ext_loader.py", line 15, in load_ext
    assert hasattr(ext, fun), f'{fun} miss in module {name}'
AssertionError: iou3d_boxes_iou_bev_forward miss in module _ext
```

\[here\]

### To Reproduce

The command you executed.

```shell
[here]
```

### Post related information

1. The output of `pip list | grep "mmcv\|mmrazor\|^torch"`
  mmcv                    1.5.0
mmcv-full               1.7.1
mmrazor                 0.3.1
torch                   1.12.1+cu113
torchaudio              0.12.1+cu113
torchvision             0.13.1+cu113
2. Your config file if you modified it or created a new one.

```python
[here]
```

3. Your train log file if you meet the problem during training.
   \[here\]
4. Other code you modified in the `mmrazor` folder.
   \[here\]

### Additional context

\[here\]

**Comment by HIT-cwh** [comment]
It seems that you have installed both mmcv and mmcv-full in the same environment. Please note that only one of them can be installed, and it is highly recommended to install the full version if CUDA is available. If you continue to experience this issue, kindly inform us, and we will be glad to assist you further.
