### ISSUE TITLE
'mmrazor is not in the Codebases registry.

### ISSUE THREAD

**Issue by JIANG3330** [open-mmlab/mmrazor#551]
### Checklist

- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

I want to use the exported `group_fisher_finetune_rtmpose-s` model, but when I execute it with the following command, I get the error "mmrazor is not in the Codebases registry.". I have successfully installed mmrazor according to the `https://mmpose.readthedocs.io/zh_CN/latest/installation.html`, but I still report an error.

command：
`$ python tools/deploy.py configs/mmpose/pose-detection_simcc_rknn-fp16_static-256x192.py ../mmpose/projects/rtmpose/rtmpose/pruning/group_fisher_finetune_rtmpose-s_8xb256-420e_aic-coco-256x192.py https://download.openmmlab.com/mmrazor/v1/pruning/group_fisher/rtmpose-s/group_fisher_prune_rtmpose-s_8xb256-420e_aic-coco-256x192.pth demo/resources/human-pose.jpg --work-dir rtmpose-ort/rtmpose-rknn6 --device cpu --show --dump-info`

output：
`06/09 17:53:20 - mmengine - WARNING - Import mmdeploy.codebase.mmrazor.deploy failedPlease check whether the module is the custom module.No module named 'mmdeploy.codebase.mmrazor'
Traceback (most recent call last):
  File "tools/deploy.py", line 338, in <module>
    main()
  File "tools/deploy.py", line 132, in main
    export2SDK(
  File "/home/itc/miniconda3/lib/python3.8/site-packages/mmdeploy-1.1.0-py3.8-linux-x86_64.egg/mmdeploy/backend/sdk/export_info.py", line 352, in export2SDK
    deploy_info = get_deploy(deploy_cfg, model_cfg, work_dir, device)
  File "/home/itc/miniconda3/lib/python3.8/site-packages/mmdeploy-1.1.0-py3.8-linux-x86_64.egg/mmdeploy/backend/sdk/export_info.py", line 267, in get_deploy
    _, customs = get_model_name_customs(
  File "/home/itc/miniconda3/lib/python3.8/site-packages/mmdeploy-1.1.0-py3.8-linux-x86_64.egg/mmdeploy/backend/sdk/export_info.py", line 61, in get_model_name_customs
    task_processor = build_task_processor(
  File "/home/itc/miniconda3/lib/python3.8/site-packages/mmdeploy-1.1.0-py3.8-linux-x86_64.egg/mmdeploy/apis/utils/utils.py", line 46, in build_task_processor
    import_codebase(codebase_type, custom_module_list)
  File "/home/itc/miniconda3/lib/python3.8/site-packages/mmdeploy-1.1.0-py3.8-linux-x86_64.egg/mmdeploy/codebase/__init__.py", line 36, in import_codebase
    codebase = get_codebase_class(codebase_type)
  File "/home/itc/miniconda3/lib/python3.8/site-packages/mmdeploy-1.1.0-py3.8-linux-x86_64.egg/mmdeploy/codebase/base/mmcodebase.py", line 86, in get_codebase_class
    return CODEBASE.build({'type': codebase.value})
  File "/home/itc/miniconda3/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/itc/miniconda3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'mmrazor is not in the Codebases registry. Please check whether the value of `mmrazor` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'`

### Post related information

1. The output of `pip list | grep "mmcv\|mmrazor\|^torch"`
mmcv                    2.0.0
mmrazor                 1.0.0       
torch                   2.0.1
torchvision             0.15.2

Could somebody help me?  Thank you so much.

**Comment by liamsun2019** [comment]
The same issue happend to me. Any update?

**Comment by dengrui-64** [comment]
The same issue happend to me. Any update?

**Comment by Y-T-G** [comment]
You should install the packages with mim instead of pip. Uninstall all of them from pip and install with mim.

**Comment by Y-T-G** [comment]
Also run `mim install -U mmengine`
