### ISSUE TITLE
[Bug]TypeError: class `MMArchitectureQuant` in mmrazor/models/algorithms/quantization/mm_architecture.py: _fuse_fx() got an unexpected keyword argument 'graph_module'

### ISSUE THREAD

**Issue by PancakeAwesome** [open-mmlab/mmrazor#553]
### Describe the bug

Traceback (most recent call last):
  File "/opt/conda/envs/torch2/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/mnt/jingcheng/mmrazor/mmrazor/models/algorithms/quantization/mm_architecture.py", line 90, in __init__
    self.qmodels = self._build_qmodels(self.architecture)
  File "/mnt/jingcheng/mmrazor/mmrazor/models/algorithms/quantization/mm_architecture.py", line 297, in _build_qmodels
    observed_module = self.quantizer.prepare(
  File "/mnt/jingcheng/mmrazor/mmrazor/models/quantizers/native_quantizer.py", line 238, in prepare
    graph_module = _fuse_fx(
TypeError: _fuse_fx() got an unexpected keyword argument 'graph_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/ptq.py", line 73, in <module>
    main()
  File "tools/ptq.py", line 66, in main
    runner = Runner.from_cfg(cfg)
  File "/opt/conda/envs/torch2/lib/python3.8/site-packages/mmengine/runner/runner.py", line 439, in from_cfg
    runner = cls(
  File "/opt/conda/envs/torch2/lib/python3.8/site-packages/mmengine/runner/runner.py", line 406, in __init__
    self.model = self.build_model(model)
  File "/opt/conda/envs/torch2/lib/python3.8/site-packages/mmengine/runner/runner.py", line 813, in build_model
    model = MODELS.build(model)
  File "/opt/conda/envs/torch2/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/envs/torch2/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 250, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/envs/torch2/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 144, in build_from_cfg
    raise type(e)(
TypeError: class `MMArchitectureQuant` in mmrazor/models/algorithms/quantization/mm_architecture.py: _fuse_fx() got an unexpected keyword argument 'graph_module'

### To Reproduce

The command you executed.

```shell
python tools/ptq.py my_configs/ptq_openvino_yolox_s_1xb32-400e_coco_calib32xb32.py
```

### Post related information

1. The output of `pip list | grep "mmcv\|mmrazor\|^torch"`
   \[here\]
2. Your config file if you modified it or created a new one.

```python
[here]
```

3. Your train log file if you meet the problem during training.
   \[here\]
4. Other code you modified in the `mmrazor` folder.
   \[here\]

### Additional context

\[here\]

**Comment by pppppM** [comment]
I apologize for the inconvenience, but I was unable to reproduce the issue. 

If the #554  is unresolved, it should not reach the `_fuse_fx` step. 
Perhaps you have made some other modifications?

You can try following the solution in #554  first and see if you still encounter this problem.

**Comment by PancakeAwesome** [comment]
> I apologize for the inconvenience, but I was unable to reproduce the issue.
> 
> If the #554 is unresolved, it should not reach the `_fuse_fx` step. Perhaps you have made some other modifications?
> 
> You can try following the solution in #554 first and see if you still encounter this problem.

ok thanks.

**Comment by saeedadeeb103** [comment]
@PancakeAwesome 
i faced this Error before its beacuse ur using torch 2.0 and they updated _fuse_fx from 

`def _fuse_fx(
    graph_module: GraphModule,
    is_qat: bool,
    fuse_custom_config: Union[FuseCustomConfig, Dict[str, Any], None] = None,
    backend_config: Union[BackendConfig, Dict[str, Any], None] = None,
) -> GraphModule:`

to -> 

`def _fuse_fx(
    model: GraphModule,
    is_qat: bool,
    fuse_custom_config: Union[FuseCustomConfig, Dict[str, Any], None] = None,
    backend_config: Union[BackendConfig, Dict[str, Any], None] = None,
) -> GraphModule:`

so just change it from inside native_quantizer.py line 238 and it should work
