### ISSUE TITLE
How to distill faster_rcnn using the cwd algorithm in mmrazor？

### ISSUE THREAD

**Issue by luoxinstart** [open-mmlab/mmrazor#555]
### Checklist

- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

I tried distilling faster_rcnn using the cwd algorithm, but after typing the following command: 
     python tools/train.py configs/distill/mmdet/cwd/cwd_fpn_frcnn_r101_frcnn_r50_1x_coco.py 
But the error says that the dataset JSON file was not found, but the JSON file I have configured in the mmdetection file, and there is no problem with the configuration, I have run through the faster_rcnn in mmdet, and put the teacher's weight file into mmrazor

### Post related information
The error message is as follows：

loading annotations into memory...
Traceback (most recent call last):
  File "C:\Users\12823\.conda\envs\pytorch\lib\site-packages\mmengine\registry\build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "c:\users\12823\mmdetection\mmdet\datasets\base_det_dataset.py", line 40, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\12823\.conda\envs\pytorch\lib\site-packages\mmengine\dataset\base_dataset.py", line 245, in __init__
    self.full_init()
  File "c:\users\12823\mmdetection\mmdet\datasets\base_det_dataset.py", line 65, in full_init
    self.data_list = self.load_data_list()
  File "c:\users\12823\mmdetection\mmdet\datasets\coco.py", line 70, in load_data_list
    self.coco = self.COCOAPI(local_path)
  File "c:\users\12823\mmdetection\mmdet\datasets\api_wrappers\coco_api.py", line 25, in __init__
    super().__init__(annotation_file=annotation_file)
  File "C:\Users\12823\.conda\envs\pytorch\lib\site-packages\pycocotools\coco.py", line 81, in __init__
    with open(annotation_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/coco/annotations/instances_train2017.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\12823\.conda\envs\pytorch\lib\site-packages\mmengine\registry\build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "C:\Users\12823\.conda\envs\pytorch\lib\site-packages\mmengine\runner\loops.py", line 44, in __init__
    super().__init__(runner, dataloader)
  File "C:\Users\12823\.conda\envs\pytorch\lib\site-packages\mmengine\runner\base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "C:\Users\12823\.conda\envs\pytorch\lib\site-packages\mmengine\runner\runner.py", line 1346, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "tools/train.py", line 121, in <module>
    main()
  File "tools/train.py", line 117, in main
    runner.train()
  File "C:\Users\12823\.conda\envs\pytorch\lib\site-packages\mmengine\runner\runner.py", line 1687, in train
    self._train_loop = self.build_train_loop(
  File "C:\Users\12823\.conda\envs\pytorch\lib\site-packages\mmengine\runner\runner.py", line 1479, in build_train_loop
    loop = LOOPS.build(
  File "C:\Users\12823\.conda\envs\pytorch\lib\site-packages\mmengine\registry\registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "C:\Users\12823\.conda\envs\pytorch\lib\site-packages\mmengine\registry\build_functions.py", line 144, in build_from_cfg
    raise type(e)(
FileNotFoundError: class `EpochBasedTrainLoop` in mmengine/runner/loops.py: class `CocoDataset` in mmdet/datasets/coco.py: [Errno 2] No such file or directory: 'data/coco/annotations/instances_train2017.json'

please help me! thanks a lot!

**Comment by luoxinstart** [comment]
you should put the dataset into mmrazor files，not in mmdet
