### ISSUE TITLE
exceptions while trying to reproduce dsnas from a readme [Bug]

### ISSUE THREAD

**Issue by MarcinBobinski** [open-mmlab/mmrazor#576]
### Describe the bug
I tried to run dsnas with the default config which is supplied with this library. 
After 14 iterations of learning, every time my program crashes.
Can you help me / tell me what I'm doing wrong ?

### To Reproduce

The command you executed.

```shell
python ./tools/train.py \
  dsnas_supernet_8xb128_in1k.py \
  --work-dir my_nas
```

### Post related information

1. The output of `pip list | grep "mmcv\|mmrazor\|^torch"`
mmcv                     2.0.1
mmrazor                  1.0.0     /home/...
torch                    2.0.0
torchaudio               2.0.0
torchvision              0.15.0
2. Your config file if you modified it or created a new one.

https://github.com/open-mmlab/mmrazor/blob/main/configs/nas/mmcls/dsnas/dsnas_subnet_8xb128_in1k.py

3. Your train log file if you meet the problem during training.
09/03 18:53:02 - mmengine - INFO - Saving checkpoint at 14 epochs
09/03 18:53:03 - mmengine - INFO - Epoch(val) [14][1/1]    accuracy/top1: 0.0000  accuracy/top5: 0.0000  data_time: 0.0727  time: 0.1288
09/03 18:53:03 - mmengine - INFO - Exp name: dsnas_supernet_8xb128_in1k_20230903_185243
09/03 18:53:03 - mmengine - INFO - Epoch(train)  [15][1/1]  architecture.base_lr: 4.9827e-01 architecture.lr: 4.9827e-01 mutator.lr: 1.0000e-03  eta: 0:01:22  time: 0.2344  data_time: 0.1147  memory: 1933  supernet.loss: 4.4424
09/03 18:53:03 - mmengine - INFO - Saving checkpoint at 15 epochs
09/03 18:53:04 - mmengine - INFO - Epoch(val) [15][1/1]    accuracy/top1: 0.0000  accuracy/top5: 0.0000  data_time: 0.0703  time: 0.1177
Traceback (most recent call last):
  File "/home/marcinwsl/dev/WUT_EE_bachelor_thesis_code/Pytorch/src/mmrazor/./tools/train.py", line 121, in <module>
    main()
  File "/home/marcinwsl/dev/WUT_EE_bachelor_thesis_code/Pytorch/src/mmrazor/./tools/train.py", line 117, in main
    runner.train()
  File "/home/marcinwsl/miniconda3/envs/mmrazor/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1745, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/marcinwsl/miniconda3/envs/mmrazor/lib/python3.9/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/home/marcinwsl/miniconda3/envs/mmrazor/lib/python3.9/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "/home/marcinwsl/miniconda3/envs/mmrazor/lib/python3.9/site-packages/mmengine/runner/loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
  File "/home/marcinwsl/dev/WUT_EE_bachelor_thesis_code/Pytorch/src/mmrazor/mmrazor/models/algorithms/nas/dsnas.py", line 165, in train_step
    self.handle_grads()
  File "/home/marcinwsl/dev/WUT_EE_bachelor_thesis_code/Pytorch/src/mmrazor/mmrazor/models/algorithms/nas/dsnas.py", line 253, in handle_grads
    self.mutator.arch_params[k].grad.data.mul_(
AttributeError: 'NoneType' object has no attribute 'data'

4. Other code you modified in the `mmrazor` folder.
I limited amount of imagenet images to just few to reproduce error faster (that's why there is [1/1] in logs)

**Comment by DonMiller9294** [comment]
Hello! It's clear that you're facing a tricky issue while running dsnas with the default config, and I'd be happy to help you figure it out.

The error you're encountering appears to be a Python AttributeError. Specifically, it's saying that the object 'NoneType' (which usually means a variable that's unexpectedly empty or undefined) doesn't have an attribute called 'data'. This error occurred during your training process after 14 iterations.

Here are a few steps to investigate and potentially resolve this issue:

1. **Check Configuration**: Review your configuration files, especially the one you provided a link to, to ensure that all the settings and parameters are correctly defined. Sometimes, these errors can arise from incorrect configurations.

2. **Check Data**: Verify the data you're using for training, as issues with data loading or preprocessing can lead to unexpected errors. Ensure that your data is properly formatted and accessible.

3. **Library Versions**: Ensure that you're using compatible versions of all the libraries you're working with, including `mmcv`, `mmrazor`, and `torch`. Mismatched versions can sometimes cause issues.

4. **Debugging**: You might consider adding some print statements or using a debugging tool to inspect the variables and their values at the point where the error occurs. This can help you pinpoint the exact source of the problem.

5. **Community Support**: Reach out to the community or the maintainers of the library (if available) for specific help on this issue. They may have encountered a similar problem before and can offer insights or solutions.

Additionally, you mentioned that you limited the amount of ImageNet images for faster reproduction of the error. While this can be helpful for debugging, it's worth checking if the error still occurs with the full dataset to ensure it's not related to the data size.

Feel free to share more details if you have them, and we can dive deeper into troubleshooting.
