### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by grpinto** [open-mmlab/mmrazor#598]
I am providing this command :

!python tools/train.py /content/mmrazor/configs/pruning/mmdet/dcff/dcff_faster_rcnn_resnet50_8xb4_coco.py 

and getting back this error, does anybody know why ?

/usr/local/lib/python3.10/dist-packages/mmcv/cnn/bricks/transformer.py:33: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv`` rather than ``mmcv-lite`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
Traceback (most recent call last):
  File "/content/mmrazor/./tools/train.py", line 121, in <module>
    main()
  File "/content/mmrazor/./tools/train.py", line 114, in main
    runner = Runner.from_cfg(cfg)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py", line 397, in __init__
    self.log_processor = self.build_log_processor(log_processor)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py", line 1650, in build_log_processor
    log_processor = LOG_PROCESSORS.build(log_processor_cfg)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py", line 98, in build_from_cfg
    obj_cls = registry.get(obj_type)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/registry.py", line 451, in get
    self.import_from_location()
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/registry.py", line 376, in import_from_location
    import_module(loc)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/mmdetection/mmdet/engine/__init__.py", line 2, in <module>
    from .hooks import *  # noqa: F401, F403
  File "/content/mmdetection/mmdet/engine/hooks/__init__.py", line 10, in <module>
    from .visualization_hook import DetVisualizationHook, TrackVisualizationHook
  File "/content/mmdetection/mmdet/engine/hooks/visualization_hook.py", line 13, in <module>
    from mmdet.datasets.samplers import TrackImgSampler
  File "/content/mmdetection/mmdet/datasets/__init__.py", line 26, in <module>
    from .utils import get_loading_pipeline
  File "/content/mmdetection/mmdet/datasets/utils.py", line 5, in <module>
    from mmdet.datasets.transforms import LoadAnnotations, LoadPanopticAnnotations
  File "/content/mmdetection/mmdet/datasets/transforms/__init__.py", line 6, in <module>
    from .formatting import (ImageToTensor, PackDetInputs, PackReIDInputs,
  File "/content/mmdetection/mmdet/datasets/transforms/formatting.py", line 11, in <module>
    from mmdet.structures.bbox import BaseBoxes
  File "/content/mmdetection/mmdet/structures/bbox/__init__.py", line 2, in <module>
    from .base_boxes import BaseBoxes
  File "/content/mmdetection/mmdet/structures/bbox/base_boxes.py", line 9, in <module>
    from mmdet.structures.mask.structures import BitmapMasks, PolygonMasks
  File "/content/mmdetection/mmdet/structures/mask/__init__.py", line 3, in <module>
    from .structures import (BaseInstanceMasks, BitmapMasks, PolygonMasks,
  File "/content/mmdetection/mmdet/structures/mask/structures.py", line 12, in <module>
    from mmcv.ops.roi_align import roi_align
  File "/usr/local/lib/python3.10/dist-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/usr/local/lib/python3.10/dist-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/usr/local/lib/python3.10/dist-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /usr/local/lib/python3.10/dist-packages/mmcv/_ext.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE

I am running it on colab

**Comment by LKJacky** [comment]
It seems a installation error of mmcv. Please reinstall mmcv with right version
