### ISSUE TITLE
[Bug] class `CustomTracer` in mmrazor/models/task_modules/tracer/fx/custom_tracer.py: __init__() takes 1 positional argument but 3 were given

### ISSUE THREAD

**Issue by RX0-Zed** [open-mmlab/mmrazor#606]
### Checklist

- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

I follow the issue #554 to implement a PTQ of YOLOX with the recommended configs, but a error is reported that "class `CustomTracer` in mmrazor/models/task_modules/tracer/fx/custom_tracer.py: __init__() takes 1 positional argument but 3 were given"

### Post related information

1. The output of `pip list | grep "mmcv\|mmrazor\|^torch"`
 
```
mmcv                    2.0.0rc4
mmrazor                 1.0.0                
torch                   1.10.2+cu113
torchvision             0.11.3+cu113
mmyolo                  0.5.0
mmdet                   3.0.0

```

2. Your config file if you modified it or created a new one.

```
base_ = [
    'mmyolo::yolov5/yolov5_n-v61_syncbn_fast_8xb16-300e_coco.py',
    '../../deploy_cfgs/mmdet/detection_openvino_dynamic-800x1344.py'
]
_base_.val_dataloader.batch_size = 32

test_cfg = dict(
    type='mmrazor.PTQLoop',
    calibrate_dataloader=_base_.val_dataloader,
    calibrate_steps=32,
)

float_checkpoint = xxx

global_qconfig = dict(
    w_observer=dict(type='mmrazor.PerChannelMinMaxObserver'),
    a_observer=dict(type='mmrazor.MovingAverageMinMaxObserver'),
    w_fake_quant=dict(type='mmrazor.FakeQuantize'),
    a_fake_quant=dict(type='mmrazor.FakeQuantize'),
    w_qscheme=dict(
        qdtype='qint8', bit=8, is_symmetry=True, is_symmetric_range=True),
    a_qscheme=dict(qdtype='quint8', bit=8, is_symmetry=True),
)

model = dict(
    _delete_=True,
    type='mmrazor.MMArchitectureQuant',
    architecture=_base_.model,
    deploy_cfg=_base_.deploy_cfg,
    float_checkpoint=float_checkpoint,
    quantizer=dict(
        type='mmrazor.OpenVINOQuantizer',
        global_qconfig=global_qconfig,
        tracer=dict(
            type='mmrazor.CustomTracer',
            skipped_methods=[
                'mmyolo.models.dense_heads.yolov5_head.YOLOv5Head.predict_by_feat',  # noqa: E501
                'mmyolo.models.dense_heads.yolov5_head.YOLOv5Head.loss_by_feat',
            ])))

model_wrapper_cfg = dict(
    type='mmrazor.MMArchitectureQuantDDP',
    broadcast_buffers=False,
    find_unused_parameters=True)

custom_hooks = []

default_hooks = dict(
    checkpoint=dict(save_best=None)
)
```

3. Your train log file if you meet the problem during training.

```
Traceback (most recent call last):
  File "/home/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/work_path/mmrazor/mmrazor/models/task_modules/tracer/fx/custom_tracer.py", line 238, in __init__
    super(CustomTracer, self).__init__(skipped_module_names,
TypeError: __init__() takes 1 positional argument but 3 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/work_path/mmrazor/mmrazor/models/quantizers/native_quantizer.py", line 133, in __init__
    super().__init__(tracer)
  File "/work_path/mmrazor/mmrazor/models/quantizers/base.py", line 27, in __init__
    self.tracer = TASK_UTILS.build(tracer)
  File "/home/conda/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 144, in build_from_cfg
    raise type(e)(
TypeError: class `CustomTracer` in mmrazor/models/task_modules/tracer/fx/custom_tracer.py: __init__() takes 1 positional argument but 3 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/work_path/mmrazor/mmrazor/models/algorithms/quantization/mm_architecture.py", line 75, in __init__
    self.quantizer = MODELS.build(quantizer)
  File "/home/conda/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/work_path/mmrazor/mmrazor/registry/registry.py", line 49, in build_razor_model_from_cfg
    razor_model = build_from_cfg(cfg, registry, default_args)
  File "/home/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 144, in build_from_cfg
    raise type(e)(
TypeError: class `OpenVINOQuantizer` in mmrazor/models/quantizers/openvino_quantizer.py: class `CustomTracer` in mmrazor/models/task_modules/tracer/fx/custom_tracer.py: __init__() takes 1 positional argument but 3 were given
```

4. Other code you modified in the `mmrazor` folder.
   
No

**Comment by Redreadblack** [comment]
hi, have you solved this? I also face the error and have no idea
